spring.application.name=TOY_4_BE
gemini.api.key=${GEMINI_API_KEY:}

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models
gemini.api.model=gemini-3.5-flash

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.sql.init.data-locations=classpath:perfume-data.sql